name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          - latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      # Login against a Docker registry
      # https://github.com/docker/login-action
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jfloff
          password: ${{ secrets.GH_ACTIONS_PAT }}
      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      -
        name: Build and push :${{ matrix.ruby }}
        uses: docker/build-push-action@v2
        with:
          context: .
          no-cache: true
          push: true
          tags: ghcr.io/jfloff/wrk2:${{ matrix.tags }}